name: AlmostTP
version: '${project.version}'
main: me.almost.tpaplugin.TPAPlugin
api-version: 1.19
authors: [ AlmostMee ]
description: A simple TP plugin.
commands:
    tpa:
       description: Use this command to teleport to someone.
       usage: /<command> <name>
    tpaccept:
      description: Use this command to accept the teleportation request of someone.
      usage: /<command>
    tpdeny:
      description: Use this command to deny the teleportation request of someone.
      usage: /<command>

